# Generated by Django 4.0.1 on 2022-01-29 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Common_Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Compliant_Type', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='PlantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planttype', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Plant_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantname', models.CharField(max_length=200)),
                ('Delivered_on', models.DateTimeField()),
                ('Location', models.CharField(max_length=300)),
                ('sample_dwarings', models.FileField(upload_to='')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataCollection.client')),
                ('Typeofplant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataCollection.plantmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Compliants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Problem_Description', models.TextField(max_length=3000)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataCollection.client')),
                ('Compliant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataCollection.common_problems')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataCollection.plant_details')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='plant_type_owned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataCollection.plantmodel'),
        ),
    ]
