# Generated by Django 4.0.1 on 2022-01-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('plant_type_owned', models.CharField(choices=[('AAC', 'AAC'), ('CLC', 'CLC')], default='', max_length=60)),
            ],
        ),
    ]
