# Generated by Django 4.0.2 on 2022-03-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataCollection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='created_blocks',
            old_name='block_count',
            new_name='block',
        ),
    ]
