# Generated by Django 4.0.1 on 2022-01-24 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataCollection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planttype', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Plant_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantname', models.CharField(max_length=200)),
                ('Delivered_on', models.DateTimeField()),
                ('Location', models.CharField(max_length=300)),
                ('sample_dwarings', models.FileField(upload_to='')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataCollection.client')),
                ('Typeofplant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataCollection.plantmodel')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='plant_type_owned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataCollection.plantmodel'),
        ),
    ]
