# Generated by Django 4.0.1 on 2022-01-24 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataCollection', '0002_plantmodel_plant_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Common_Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Compliant_Type', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Compliants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Problem_Description', models.TextField(max_length=3000)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataCollection.client')),
                ('Compliant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataCollection.common_problems')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataCollection.plant_details')),
            ],
        ),
    ]
